version: '3.8'
services:
  redis:
    image: redis:7
    container_name: bookstore_redis
    ports:
      - "6379:6379"
    restart: unless-stopped


    #docker-compose up -d redis
    #docker-compose down