#spring.application.name=virtualBookStore
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BOOKS
    username: postgres
    password: 19788707
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 7070
